/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("my-project/public/meModel.gltf");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="metarig" position={[2.526, 1.333, -0.879]} scale={0.989}>
          <skinnedMesh
            name="Cube002"
            geometry={nodes.Cube002.geometry}
            material={materials.Material}
            skeleton={nodes.Cube002.skeleton}
          />
          <primitive object={nodes.footL} />
          <primitive object={nodes.footR} />
          <primitive object={nodes.Bone} />
        </group>
        <group
          name="metarig001"
          position={[-15.259, 1.333, -0.879]}
          scale={1.598}
        >
          <group
            name="footL_1"
            position={[0.134, 0.106, -0.192]}
            rotation={[1.953, 0.023, -0.006]}
          >
            <group
              name="toeL_1"
              position={[0, 0.224, 0]}
              rotation={[2.78, 0.023, 3.123]}
            />
          </group>
          <group
            name="footR_1"
            position={[-0.134, 0.106, -0.192]}
            rotation={[1.953, -0.023, 0.006]}
          >
            <group
              name="toeR_1"
              position={[0, 0.224, 0]}
              rotation={[2.78, -0.023, -3.123]}
            />
          </group>
          <group name="Bone_1">
            <group
              name="spine_1"
              position={[0, 0.965, -0.261]}
              rotation={[0.183, 0, 0]}
            >
              <group
                name="spine001_1"
                position={[0, 0.13, 0]}
                rotation={[-0.112, 0, 0]}
              >
                <group
                  name="spine002_1"
                  position={[0, 0.142, 0]}
                  rotation={[-0.208, 0, 0]}
                >
                  <group
                    name="spine003_1"
                    position={[0, 0.202, 0]}
                    rotation={[0.241, 0, 0]}
                  >
                    <group
                      name="spine004_1"
                      position={[0, 0.203, 0]}
                      rotation={[0.344, 0, 0]}
                    >
                      <group
                        name="spine005_1"
                        position={[0, 0.051, 0]}
                        rotation={[-0.397, 0.011, 0.007]}
                      >
                        <group
                          name="spine006_1"
                          position={[0, 0.054, 0]}
                          rotation={[-0.043, -0.009, -0.009]}
                        />
                      </group>
                    </group>
                    <group
                      name="shoulderL_1"
                      position={[0.022, 0.2, 0.096]}
                      rotation={[-1.674, 0, -1.235]}
                    >
                      <group
                        name="upper_armL_1"
                        position={[-0.001, 0.219, -0.039]}
                        rotation={[1.56, 1.245, -2.438]}
                      >
                        <group
                          name="forearmL_1"
                          position={[0, 0.289, 0]}
                          rotation={[0.082, 0.11, 0.018]}
                        >
                          <group
                            name="handL_1"
                            position={[0, 0.31, 0]}
                            rotation={[-0.089, -0.072, 0.1]}
                          />
                        </group>
                      </group>
                    </group>
                    <group
                      name="shoulderR_1"
                      position={[-0.022, 0.2, 0.096]}
                      rotation={[-1.674, 0, 1.235]}
                    >
                      <group
                        name="upper_armR_1"
                        position={[0.001, 0.219, -0.039]}
                        rotation={[1.56, -1.245, 2.438]}
                      >
                        <group
                          name="forearmR_1"
                          position={[0, 0.289, 0]}
                          rotation={[0.082, -0.11, -0.018]}
                        >
                          <group
                            name="handR_1"
                            position={[0, 0.31, 0]}
                            rotation={[-0.089, 0.072, -0.1]}
                          />
                        </group>
                      </group>
                    </group>
                    <group
                      name="breastL_1"
                      position={[0.118, 0.028, 0.022]}
                      rotation={[-1.674, 0, Math.PI]}
                    />
                    <group
                      name="breastR_1"
                      position={[-0.118, 0.028, 0.022]}
                      rotation={[-1.674, 0, Math.PI]}
                    />
                  </group>
                </group>
              </group>
              <group
                name="pelvisL_1"
                position={[0, -0.021, 0.028]}
                rotation={[-1.872, -0.659, -2.033]}
              />
              <group
                name="pelvisR_1"
                position={[0, -0.021, 0.028]}
                rotation={[-1.872, 0.659, 2.033]}
              />
              <group
                name="thighL_1"
                position={[0.146, 0.058, 0.049]}
                rotation={[2.929, -0.003, 0.01]}
              >
                <group
                  name="shinL_1"
                  position={[0, 0.518, 0]}
                  rotation={[0.044, -0.004, 0.006]}
                />
              </group>
              <group
                name="thighR_1"
                position={[-0.146, 0.058, 0.049]}
                rotation={[2.929, 0.003, -0.011]}
              >
                <group
                  name="shinR_1"
                  position={[0, 0.518, 0]}
                  rotation={[0.044, 0.015, -0.004]}
                />
              </group>
            </group>
            <group
              name="shinIKL_1"
              position={[0.134, 0.106, -0.192]}
              rotation={[-Math.PI / 2, 0.014, 0]}
            />
            <group
              name="shinIKR_1"
              position={[-0.134, 0.106, -0.192]}
              rotation={[-Math.PI / 2, -0.014, 0]}
            />
            <group
              name="thighIKL_1"
              position={[0.141, 0.495, 0.269]}
              rotation={[Math.PI / 2, -0.009, 0]}
            />
            <group
              name="thighIKR_1"
              position={[-0.141, 0.495, 0.269]}
              rotation={[Math.PI / 2, 0.009, 0]}
            />
            <group
              name="forearmIKL_1"
              position={[0.616, 1.127, -0.189]}
              rotation={[Math.PI / 2, 0.676, -Math.PI]}
            />
            <group
              name="forearmIKR_1"
              position={[-0.616, 1.127, -0.189]}
              rotation={[Math.PI / 2, -0.676, -Math.PI]}
            />
            <group
              name="upper_armIKL_1"
              position={[0.413, 1.361, -0.547]}
              rotation={[Math.PI / 2, 0.76, -Math.PI]}
            />
            <group
              name="upper_armIKR_1"
              position={[-0.413, 1.361, -0.547]}
              rotation={[Math.PI / 2, -0.76, -Math.PI]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("my-project/public/meModel.gltf");


// rembrandt

// city
// Made by @NikkitaFTW & contributors inspired by the gltfjsx cli

