/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 bedroomToExport.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/bedroomToExport.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="metarig" position={[-1.318, 0.181, -1.529]} scale={1.043}>
          <primitive object={nodes.footL} />
          <primitive object={nodes.footR} />
          <primitive object={nodes.Bone} />
          <skinnedMesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials.Material} skeleton={nodes.Cube002.skeleton} />
        </group>
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials.Material} position={[2.787, -4.123, 2.561]} scale={[5.351, -0.064, 5.351]} />
        <mesh name="Cube004" geometry={nodes.Cube004.geometry} material={materials.Material} position={[-2.685, 0.814, -3.4]} rotation={[0, Math.PI / 2, 0]} scale={0.367} />
        <mesh name="Cube011" geometry={nodes.Cube011.geometry} material={materials.Material} position={[-2.833, 4.412, -0.635]} rotation={[0, Math.PI / 2, 0]} scale={[4.407, 0.144, 1]} />
        <mesh name="Cube012" geometry={nodes.Cube012.geometry} material={materials.Material} position={[-0.926, 0.155, 2.522]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Cube013" geometry={nodes.Cube013.geometry} material={materials.Material} position={[1.283, 0.009, -1.03]} />
        <mesh name="Cube014" geometry={nodes.Cube014.geometry} material={materials.Material} position={[-0.926, 0.209, 2.522]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Cube015" geometry={nodes.Cube015.geometry} material={materials.Material} position={[-0.926, 0.098, 2.527]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials.Material} position={[-2.823, 0.198, 1.375]} scale={[0.078, 0.017, 0.078]} />
        <mesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials.Material} position={[-3.936, 0.198, 1.377]} scale={[0.078, 0.017, 0.078]} />
        <mesh name="Cube016" geometry={nodes.Cube016.geometry} material={materials.Material} position={[-3.313, 0.938, 2.957]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Cube017" geometry={nodes.Cube017.geometry} material={materials.Material} position={[-3.195, 0.927, 2.957]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Cube018" geometry={nodes.Cube018.geometry} material={materials.Material} position={[-2.833, 3.233, -0.635]} rotation={[0, Math.PI / 2, 0]} scale={[4.407, 0.144, 1]} />
        <mesh name="Cube019" geometry={nodes.Cube019.geometry} material={materials.Material} position={[1.326, 0.101, 1.568]} scale={[0.284, 1, 0.824]} />
        <mesh name="Cube020" geometry={nodes.Cube020.geometry} material={materials.Material} position={[-4.266, 2.08, 2.567]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.399, 1, 0.251]} />
        <mesh name="Cube021" geometry={nodes.Cube021.geometry} material={materials.Material} position={[-2.568, 1.867, -4.323]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.275, 1, 0.523]} />
        <mesh name="Cube023" geometry={nodes.Cube023.geometry} material={materials.Material} position={[-3.852, 3.171, 0.545]} rotation={[0, Math.PI / 2, 0]} scale={0.158} />
        <mesh name="Cube024" geometry={nodes.Cube024.geometry} material={materials.Material} position={[-3.852, 3.171, -0.032]} rotation={[0, Math.PI / 2, 0]} scale={0.158} />
        <mesh name="Cube025" geometry={nodes.Cube025.geometry} material={materials.Material} position={[-3.852, 3.171, -0.566]} rotation={[0, Math.PI / 2, 0]} scale={0.158} />
        <mesh name="Cube026" geometry={nodes.Cube026.geometry} material={materials.Material} position={[-3.852, 3.171, -1.127]} rotation={[0, Math.PI / 2, 0]} scale={0.158} />
        <mesh name="Cube027" geometry={nodes.Cube027.geometry} material={materials.Material} position={[-3.852, 3.171, -1.752]} rotation={[0, Math.PI / 2, 0]} scale={0.158} />
        <mesh name="Cube029" geometry={nodes.Cube029.geometry} material={materials.Material} position={[-1.885, -0.621, 3.095]} rotation={[Math.PI, -1.272, Math.PI]} scale={[0.49, 0.06, 0.49]} />
        <mesh name="Cylinder003" geometry={nodes.Cylinder003.geometry} material={materials.Material} position={[-1.913, 0.073, 3.092]} rotation={[Math.PI, -1.272, Math.PI]} scale={0.249} />
        <mesh name="Cylinder004" geometry={nodes.Cylinder004.geometry} material={materials.Material} position={[-2.478, 0.227, 3.281]} rotation={[Math.PI / 2, 0, 2.807]} scale={[0.059, 0.037, 0.059]} />
        <mesh name="Cylinder005" geometry={nodes.Cylinder005.geometry} material={materials.Material} position={[-1.566, 0.227, 2.591]} rotation={[Math.PI / 2, 0, 2.214]} scale={[0.059, 0.037, 0.059]} />
        <mesh name="Cylinder006" geometry={nodes.Cylinder006.geometry} material={materials.Material} position={[-2.281, 0.227, 2.612]} rotation={[Math.PI / 2, 0, 0.927]} scale={[0.059, 0.037, 0.059]} />
        <mesh name="Cylinder007" geometry={nodes.Cylinder007.geometry} material={materials.Material} position={[-1.331, 0.227, 3.274]} rotation={[Math.PI / 2, 0, -2.822]} scale={[0.059, 0.037, 0.059]} />
        <mesh name="Cylinder008" geometry={nodes.Cylinder008.geometry} material={materials.Material} position={[-1.893, 0.239, 3.695]} rotation={[Math.PI / 2, 0, -1.581]} scale={[0.059, 0.037, 0.059]} />
        <mesh name="Cylinder016" geometry={nodes.Cylinder016.geometry} material={materials.Material} position={[3.501, -0.243, -3.518]} scale={0.729} />
        <mesh name="Cylinder018" geometry={nodes.Cylinder018.geometry} material={materials.Material} position={[3.554, 1.239, -3.7]} scale={0.032} />
        <mesh name="Cylinder019" geometry={nodes.Cylinder019.geometry} material={materials.Material} position={[3.332, 1.239, -3.569]} scale={0.032} />
        <mesh name="Cylinder020" geometry={nodes.Cylinder020.geometry} material={materials.Material} position={[3.685, 1.239, -3.517]} scale={0.032} />
        <mesh name="Cylinder021" geometry={nodes.Cylinder021.geometry} material={materials.Material} position={[3.503, 1.239, -3.401]} scale={0.032} />
        <mesh name="Cylinder023" geometry={nodes.Cylinder023.geometry} material={materials.Material} position={[3.513, -0.63, -3.287]} scale={[0.055, 0.058, 0.058]} />
        <mesh name="Cylinder024" geometry={nodes.Cylinder024.geometry} material={materials.Material} position={[3.764, -0.63, -3.383]} rotation={[0, 1.343, 0]} scale={[0.055, 0.058, 0.058]} />
        <mesh name="Cylinder025" geometry={nodes.Cylinder025.geometry} material={materials.Material} position={[3.296, -0.63, -3.37]} rotation={[0, -1.398, 0]} scale={[0.055, 0.058, 0.058]} />
        <mesh name="Cylinder026" geometry={nodes.Cylinder026.geometry} material={materials.Material} position={[3.388, -0.877, -3.337]} rotation={[0, -0.689, 0]} scale={[0.064, 0.068, 0.068]} />
        <mesh name="Cylinder027" geometry={nodes.Cylinder027.geometry} material={materials.Material} position={[3.691, -0.68, -3.341]} rotation={[0, 0.592, 0]} scale={[0.056, 0.06, 0.06]} />
        <mesh name="Cylinder028" geometry={nodes.Cylinder028.geometry} material={materials.Material} position={[3.507, -0.695, -3.746]} rotation={[-Math.PI, -0.087, -Math.PI]} scale={[0.057, 0.061, 0.061]} />
        <mesh name="Cylinder029" geometry={nodes.Cylinder029.geometry} material={materials.Material} position={[3.286, -0.685, -3.612]} rotation={[-Math.PI, -1.43, -Math.PI]} scale={[0.057, 0.061, 0.061]} />
        <mesh name="Cylinder030" geometry={nodes.Cylinder030.geometry} material={materials.Material} position={[3.741, -0.672, -3.59]} rotation={[-Math.PI, 1.311, -Math.PI]} scale={[0.056, 0.06, 0.06]} />
        <mesh name="Cylinder031" geometry={nodes.Cylinder031.geometry} material={materials.Material} position={[3.644, -0.675, -3.708]} rotation={[-Math.PI, 0.602, -Math.PI]} scale={[0.056, 0.06, 0.06]} />
        <mesh name="Cylinder032" geometry={nodes.Cylinder032.geometry} material={materials.Material} position={[3.353, -0.651, -3.687]} rotation={[Math.PI, -0.679, Math.PI]} scale={[0.055, 0.059, 0.059]} />
        <mesh name="Cylinder033" geometry={nodes.Cylinder033.geometry} material={materials.Material} position={[3.495, -0.162, -3.468]} rotation={[0, 0.104, 0]} scale={[0.055, 0.058, 0.058]} />
        <mesh name="Cylinder034" geometry={nodes.Cylinder034.geometry} material={materials.Material} position={[3.578, -0.313, -3.411]} rotation={[0, -1.45, 0]} scale={[0.057, 0.061, 0.061]} />
        <mesh name="Cylinder035" geometry={nodes.Cylinder035.geometry} material={materials.Material} position={[3.495, -0.513, -3.477]} rotation={[0, 0.078, 0]} scale={[0.055, 0.058, 0.058]} />
        <mesh name="Cylinder036" geometry={nodes.Cylinder036.geometry} material={materials.Material} position={[3.434, -0.34, -3.422]} rotation={[0, 1.273, 0]} scale={[0.055, 0.058, 0.058]} />
        <mesh name="Cylinder037" geometry={nodes.Cylinder037.geometry} material={materials.Material} position={[3.649, -0.195, -3.593]} rotation={[0, 0.433, 0]} scale={[0.06, 0.064, 0.064]} />
        <mesh name="Cylinder038" geometry={nodes.Cylinder038.geometry} material={materials.Material} position={[3.608, -0.712, -3.485]} rotation={[-Math.PI, 1.136, -Math.PI]} scale={[0.06, 0.064, 0.064]} />
        <mesh name="Cylinder039" geometry={nodes.Cylinder039.geometry} material={materials.Material} position={[3.634, -0.503, -3.449]} rotation={[-Math.PI, 0.629, -Math.PI]} scale={[0.06, 0.064, 0.064]} />
        <mesh name="Cylinder040" geometry={nodes.Cylinder040.geometry} material={materials.Material} position={[3.609, 0.442, -3.515]} rotation={[-Math.PI, 1.54, -Math.PI]} scale={[0.056, 0.06, 0.06]} />
        <mesh name="Cylinder041" geometry={nodes.Cylinder041.geometry} material={materials.Material} position={[3.38, -0.518, -3.509]} rotation={[-Math.PI, -0.66, -Math.PI]} scale={[0.06, 0.064, 0.064]} />
        <mesh name="Cylinder042" geometry={nodes.Cylinder042.geometry} material={materials.Material} position={[3.376, 0.608, -3.513]} rotation={[-Math.PI, -0.66, -Math.PI]} scale={[0.051, 0.055, 0.055]} />
        <mesh name="Cylinder043" geometry={nodes.Cylinder043.geometry} material={materials.Material} position={[3.559, 0.333, -3.614]} rotation={[-Math.PI, -0.056, -Math.PI]} scale={[0.057, 0.061, 0.061]} />
        <mesh name="Cylinder044" geometry={nodes.Cylinder044.geometry} material={materials.Material} position={[3.555, -0.165, -3.616]} rotation={[-Math.PI, -0.056, -Math.PI]} scale={[0.06, 0.064, 0.064]} />
        <mesh name="Cylinder045" geometry={nodes.Cylinder045.geometry} material={materials.Material} position={[3.548, -0.711, -3.621]} rotation={[-Math.PI, 0.066, -Math.PI]} scale={[0.06, 0.065, 0.065]} />
        <mesh name="Cylinder046" geometry={nodes.Cylinder046.geometry} material={materials.Material} position={[3.591, -0.143, -3.769]} rotation={[0, -0.475, 0]} scale={[0.06, 0.064, 0.064]} />
        <mesh name="Cylinder047" geometry={nodes.Cylinder047.geometry} material={materials.Material} position={[3.567, 0.181, -3.785]} rotation={[0, -0.16, 0]} scale={[0.06, 0.064, 0.064]} />
        <mesh name="Cylinder048" geometry={nodes.Cylinder048.geometry} material={materials.Material} position={[3.602, -0.504, -3.756]} rotation={[0, -0.686, 0]} scale={[0.056, 0.06, 0.06]} />
        <mesh name="Cylinder049" geometry={nodes.Cylinder049.geometry} material={materials.Material} position={[3.594, 0.652, -3.767]} rotation={[0, -0.534, 0]} scale={[0.05, 0.054, 0.054]} />
        <mesh name="Cylinder050" geometry={nodes.Cylinder050.geometry} material={materials.Material} position={[3.413, 0.346, -3.566]} rotation={[0, -1.568, 0]} scale={[0.054, 0.058, 0.058]} />
        <mesh name="Cylinder051" geometry={nodes.Cylinder051.geometry} material={materials.Material} position={[3.401, 0.055, -3.534]} rotation={[Math.PI, -1.056, Math.PI]} scale={[0.056, 0.06, 0.06]} />
        <mesh name="Cylinder052" geometry={nodes.Cylinder052.geometry} material={materials.Material} position={[3.409, -0.591, -3.586]} rotation={[0, -1.355, 0]} scale={[0.056, 0.06, 0.06]} />
        <mesh name="Cylinder053" geometry={nodes.Cylinder053.geometry} material={materials.Material} position={[3.663, -0.464, -3.586]} rotation={[0, 0.342, 0]} scale={[0.055, 0.058, 0.058]} />
        <mesh name="Cylinder054" geometry={nodes.Cylinder054.geometry} material={materials.Material} position={[3.643, -0.097, -3.442]} rotation={[-Math.PI, 0.503, -Math.PI]} scale={[0.06, 0.064, 0.064]} />
        <mesh name="Cylinder055" geometry={nodes.Cylinder055.geometry} material={materials.Material} position={[3.605, -0.361, -3.511]} rotation={[-Math.PI, 1.494, -Math.PI]} scale={[0.06, 0.064, 0.064]} />
        <mesh name="Cylinder056" geometry={nodes.Cylinder056.geometry} material={materials.Material} position={[3.618, 0.226, -3.57]} rotation={[0, 0.886, 0]} scale={[0.056, 0.06, 0.06]} />
        <mesh name="Cylinder057" geometry={nodes.Cylinder057.geometry} material={materials.Material} position={[3.594, -0.549, -3.626]} rotation={[-Math.PI, -0.454, -Math.PI]} scale={[0.06, 0.064, 0.064]} />
        <mesh name="Cylinder058" geometry={nodes.Cylinder058.geometry} material={materials.Material} position={[3.379, 0.283, -3.634]} rotation={[0, -0.579, 0]} scale={[0.053, 0.057, 0.057]} />
        <mesh name="Cylinder059" geometry={nodes.Cylinder059.geometry} material={materials.Material} position={[3.391, -0.09, -3.621]} rotation={[0, -0.802, 0]} scale={[0.056, 0.06, 0.06]} />
        <mesh name="Cylinder060" geometry={nodes.Cylinder060.geometry} material={materials.Material} position={[3.706, -0.025, -3.6]} rotation={[0, -0.286, 0]} scale={[0.06, 0.064, 0.064]} />
        <mesh name="Cylinder061" geometry={nodes.Cylinder061.geometry} material={materials.Material} position={[3.507, -0.379, -3.628]} rotation={[-Math.PI, 0.594, -Math.PI]} scale={[0.06, 0.065, 0.065]} />
        <mesh name="Cylinder062" geometry={nodes.Cylinder062.geometry} material={materials.Material} position={[3.384, 0.602, -3.501]} rotation={[-Math.PI, -0.66, -Math.PI]} scale={[0.06, 0.064, 0.064]} />
        <mesh name="Cylinder063" geometry={nodes.Cylinder063.geometry} material={materials.Material} position={[3.365, 0.718, -3.638]} rotation={[0, -0.44, 0]} scale={[0.055, 0.059, 0.059]} />
        <mesh name="Cylinder064" geometry={nodes.Cylinder064.geometry} material={materials.Material} position={[3.627, 0.774, -3.567]} rotation={[0, 0.886, 0]} scale={[0.053, 0.057, 0.057]} />
        <mesh name="Cylinder065" geometry={nodes.Cylinder065.geometry} material={materials.Material} position={[3.682, 0.543, -3.591]} rotation={[0, 0.078, 0]} scale={[0.055, 0.06, 0.06]} />
        <mesh name="Cylinder066" geometry={nodes.Cylinder066.geometry} material={materials.Material} position={[3.57, 0.855, -3.781]} rotation={[0, -0.16, 0]} scale={[0.054, 0.058, 0.058]} />
        <mesh name="Cylinder067" geometry={nodes.Cylinder067.geometry} material={materials.Material} position={[3.478, 0.632, -3.704]} rotation={[0, 1.473, 0]} scale={[0.054, 0.058, 0.058]} />
        <mesh name="Cylinder068" geometry={nodes.Cylinder068.geometry} material={materials.Material} position={[3.605, 0.225, -3.645]} rotation={[Math.PI, -0.684, Math.PI]} scale={[0.053, 0.057, 0.057]} />
        <mesh name="Cylinder069" geometry={nodes.Cylinder069.geometry} material={materials.Material} position={[3.601, 0.523, -3.626]} rotation={[Math.PI, -0.579, Math.PI]} scale={[0.06, 0.064, 0.064]} />
        <mesh name="Cylinder070" geometry={nodes.Cylinder070.geometry} material={materials.Material} position={[3.481, 0.265, -3.663]} rotation={[-Math.PI, 1.154, -Math.PI]} scale={[0.056, 0.06, 0.06]} />
        <mesh name="Cylinder071" geometry={nodes.Cylinder071.geometry} material={materials.Material} position={[3.417, -0.353, -3.544]} rotation={[-Math.PI, -1.313, -Math.PI]} scale={[0.06, 0.064, 0.064]} />
        <mesh name="Cylinder072" geometry={nodes.Cylinder072.geometry} material={materials.Material} position={[3.614, -0.276, -3.646]} rotation={[-Math.PI, -0.84, -Math.PI]} scale={[0.06, 0.064, 0.064]} />
        <mesh name="Cylinder073" geometry={nodes.Cylinder073.geometry} material={materials.Material} position={[3.5, 0.665, -3.642]} rotation={[-Math.PI, 0.738, -Math.PI]} scale={[0.06, 0.064, 0.064]} />
        <mesh name="Cylinder074" geometry={nodes.Cylinder074.geometry} material={materials.Material} position={[3.456, 0.97, -3.59]} rotation={[0.193, -1.369, 0.189]} scale={[0.051, 0.055, 0.055]} />
        <mesh name="Cylinder075" geometry={nodes.Cylinder075.geometry} material={materials.Material} position={[3.584, 0.893, -3.627]} rotation={[Math.PI, -0.403, Math.PI]} scale={[0.057, 0.061, 0.061]} />
        <mesh name="Cube022" geometry={nodes.Cube022.geometry} material={materials.Material} position={[-4.028, 2.106, 0.71]} rotation={[0, -Math.PI / 2, 0]} scale={[0.042, 0.261, 0.261]} />
        <mesh name="Cube035" geometry={nodes.Cube035.geometry} material={materials.Material} position={[-4.028, 2.106, 0.574]} rotation={[0, -Math.PI / 2, 0]} scale={[0.042, 0.261, 0.261]} />
        <mesh name="Cube036" geometry={nodes.Cube036.geometry} material={materials.Material} position={[-4.028, 2.106, 0.443]} rotation={[0, -Math.PI / 2, 0]} scale={[0.042, 0.261, 0.261]} />
        <mesh name="Cube037" geometry={nodes.Cube037.geometry} material={materials.Material} position={[-4.028, 2.106, 0.308]} rotation={[0, -Math.PI / 2, 0]} scale={[0.042, 0.261, 0.261]} />
        <mesh name="Cube038" geometry={nodes.Cube038.geometry} material={materials.Material} position={[-4.028, 2.106, 0.168]} rotation={[0, -Math.PI / 2, 0]} scale={[0.042, 0.261, 0.261]} />
        <mesh name="Cube039" geometry={nodes.Cube039.geometry} material={materials.Material} position={[-4.028, 2.106, 0.032]} rotation={[0, -Math.PI / 2, 0]} scale={[0.042, 0.261, 0.261]} />
        <mesh name="Cube040" geometry={nodes.Cube040.geometry} material={materials.Material} position={[-4.028, 2.106, -0.099]} rotation={[0, -Math.PI / 2, 0]} scale={[0.042, 0.261, 0.261]} />
        <mesh name="Cube041" geometry={nodes.Cube041.geometry} material={materials.Material} position={[-4.028, 2.106, -0.234]} rotation={[0, -Math.PI / 2, 0]} scale={[0.042, 0.261, 0.261]} />
        <mesh name="Cube042" geometry={nodes.Cube042.geometry} material={materials.Material} position={[-4.028, 2.106, -0.37]} rotation={[0, -Math.PI / 2, 0]} scale={[0.042, 0.261, 0.261]} />
        <mesh name="Cube043" geometry={nodes.Cube043.geometry} material={materials.Material} position={[-4.028, 2.106, -0.505]} rotation={[0, -Math.PI / 2, 0]} scale={[0.042, 0.261, 0.261]} />
        <mesh name="Cube044" geometry={nodes.Cube044.geometry} material={materials.Material} position={[-4.028, 2.106, -0.636]} rotation={[0, -Math.PI / 2, 0]} scale={[0.042, 0.261, 0.261]} />
        <mesh name="Cube045" geometry={nodes.Cube045.geometry} material={materials.Material} position={[-4.028, 2.106, -0.772]} rotation={[0, -Math.PI / 2, 0]} scale={[0.042, 0.261, 0.261]} />
        <mesh name="Cube048" geometry={nodes.Cube048.geometry} material={materials.Material} position={[-3.408, 1.571, 1.465]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[0.042, 0.261, 0.261]} />
        <mesh name="Cube049" geometry={nodes.Cube049.geometry} material={materials.Material} position={[-2.502, 1.493, -1.532]} rotation={[0, Math.PI / 2, 0]} scale={0.677} />
        <mesh name="Cube054" geometry={nodes.Cube054.geometry} material={materials.Material} position={[0.031, 0.105, 0.144]} scale={[5.351, -0.064, 5.351]} />
        <mesh name="Cube055" geometry={nodes.Cube055.geometry} material={materials.Material} position={[2.787, 1.438, 2.561]} scale={[5.351, -0.064, 5.351]} />
        <mesh name="Cube056" geometry={nodes.Cube056.geometry} material={materials.Material} position={[-4.17, 0.653, -1.259]} rotation={[0, Math.PI / 2, 0]} scale={0.486} />
        <mesh name="Cube058" geometry={nodes.Cube058.geometry} material={materials.Material} position={[7.049, 0.271, -4.357]} scale={[3.387, 0.13, 0.098]} />
        <mesh name="Cube060" geometry={nodes.Cube060.geometry} material={materials.Material} position={[-4.105, 0.342, 2.63]} rotation={[0, Math.PI / 2, 0]} scale={[1.166, 0.13, 0.098]} />
        <mesh name="MrFrog" geometry={nodes.MrFrog.geometry} material={materials['Material.001']} position={[0.739, 2.181, -3.8]} rotation={[-1.227, -0.238, -0.673]} />
        <mesh name="MrFrog001" geometry={nodes.MrFrog001.geometry} material={materials['Material.001']} position={[0.868, 2.284, -3.701]} rotation={[1.283, 0.1, 0.751]} />
        <mesh name="MrFrog002" geometry={nodes.MrFrog002.geometry} material={materials['Material.001']} position={[0.911, 2.248, -3.738]} rotation={[0.681, -0.407, 0.621]} />
        <mesh name="MrFrog003" geometry={nodes.MrFrog003.geometry} material={materials['Material.001']} position={[0.633, 2.449, -3.657]} rotation={[0.003, -0.683, 0.002]} />
        <mesh name="MrFrog004" geometry={nodes.MrFrog004.geometry} material={materials['Material.001']} position={[0.629, 2.384, -3.653]} rotation={[0.296, -0.66, 0.194]} />
        <mesh name="MrFrog005" geometry={nodes.MrFrog005.geometry} material={materials['Material.001']} position={[0.836, 2.043, -3.709]} rotation={[-1.082, -0.344, -0.624]} />
        <mesh name="MrFrog006" geometry={nodes.MrFrog006.geometry} material={materials['Material.001']} position={[0.802, 1.992, -3.671]} rotation={[-0.101, -0.681, -0.067]} />
        <mesh name="MrFrog007" geometry={nodes.MrFrog007.geometry} material={materials['Material.001']} position={[0.628, 2.401, -3.651]} rotation={[0.218, -0.671, 0.144]} />
        <mesh name="MrFrog008" geometry={nodes.MrFrog008.geometry} material={materials['Material.001']} position={[0.594, 2.29, -3.863]} rotation={[-0.925, -0.595, -0.674]} />
        <mesh name="MrFrog009" geometry={nodes.MrFrog009.geometry} material={materials['Material.001']} position={[0.551, 2.252, -3.828]} rotation={[-1.96, 0.208, -0.777]} />
        <mesh name="MrFrog010" geometry={nodes.MrFrog010.geometry} material={materials['Material.001']} position={[0.664, 2.032, -3.93]} rotation={[0.772, -0.519, 0.48]} />
        <mesh name="MrFrog011" geometry={nodes.MrFrog011.geometry} material={materials['Material.001']} position={[0.697, 1.976, -3.967]} rotation={[1.144, -0.301, 0.647]} />
        <group name="KingFrog_Hat" position={[1.821, 2.353, -3.786]} rotation={[0.114, -0.525, 0.057]} scale={0.007}>
          <mesh name="Cylinder076" geometry={nodes.Cylinder076.geometry} material={materials['Material.004']} />
          <mesh name="Cylinder076_1" geometry={nodes.Cylinder076_1.geometry} material={materials['Material.002']} />
        </group>
        <mesh name="Sock_Hat" geometry={nodes.Sock_Hat.geometry} material={materials['Material.003']} position={[0.605, 2.482, -3.617]} rotation={[1.806, 0.191, -2.674]} scale={0.044} />
        <mesh name="Cube028" geometry={nodes.Cube028.geometry} material={materials.Material} position={[-0.259, 0.548, -3.1]} rotation={[0, 0.085, 0]} scale={0.469} />
        <mesh name="Cylinder137" geometry={nodes.Cylinder137.geometry} material={materials.Material} position={[2.508, 6.303, 2.817]} scale={0.109} />
      </group>
    </group>
  )
}

useGLTF.preload('/bedroomToExport.gltf')
