/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 scene.gltf 
Author: Joel Anderson (https://sketchfab.com/joel3d)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/tyrannosarus-rex-free-model-e18c433cdd1c49f8ac152348b7384037
Title: Tyrannosarus rex (Free model)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.SkinColor} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.eyeColor} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.blackMatteColor} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.eyeTransparentColor} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.eyeTransparentColor} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.eyeColor} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.blackMatteColor} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.teethTexture} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.clawColor} />
    </group>
  )
}

useGLTF.preload('/scene.gltf')
